### ISSUE TITLE
Add 0-subdomain

### ISSUE THREAD

**Issue by Merovius** [cutenode/1x.engineer#101]
As a 0.1x engineer, I would appreciate a place to point people at to inform them about this underrepresented breed of engineers. https://0.1x.engineer/ would be perfect for that. ;)

**Comment by cherscarlett** [comment]
Hey @Merovius - this sounds hysterical,  but I'd love to address your concerns here, instead of splitting into two documents. The spirit of this document is that you are a contributing member of any team of any size (including just yourself!), OSS, work, or just learning, and if you feel that something in the current document is too strict or too specific, I'd love to fix it to be more inclusive. 💓
