### ISSUE TITLE
Sour grapes?

### ISSUE THREAD

**Issue by chasm** [cutenode/1x.engineer#174]
Maybe it's just me, but this comes across as sour grapes. A 10x engineer, if such exist, is ten times more productive than a 1x engineer. By definition.

Nothing else can be said about 10x vs. 1x engineers. All of the qualities you list for the 1x engineer here can apply equally to the 10x engineer, except the 10x engineer is ten times more productive. Again, by definition.

I've met easily a hundred 1x devs in my career, and a great many of them:

- Don't give credit, due or not
- Don't create community or share knowledge (many are trolls)
- Work way too many hours and still only produce 1x or less
- Have no concept of healthy balances of any kind
- Have no arbitrary contribution scores so can't be measured by them, possibly deliberately
- Write unreadable code; hell, write _complete garbage code_ shamelessly
- Almost never read the docs and certainly never write or update them
- Regularly brag about how much they know despite being sublimely ignorant (see Dunning-Kruger)
- Can't be arsed to help teammates or celebrate their "wins"
- Can't be bothered to ask questions
- Snark on code reviews (and are often wrong) and try to avoid them for their own code
- Are passive-aggressive little shits who make everyone around them hate work
- Never admit when they're wrong
- _Think_ that they are 10x engineers

And on and on and on. Everyone has met these coders and _simple arithmetic shows that almost all of them are 1x or 1x- coders_.

I think that you may be confusing 10x coders (and I doubt that you've ever met even one) with _assholes_, of which there is a surplus, as this repo shows.

The people I've met who were close to 10x coders have generally been the kindest and most helpful of coworkers, always ready to lend a hand or to mentor others. And guess what! They have the time to do so _because they get their work done so quickly_ and without fuss or excuses.

But as Dunning-Kruger predicted (and didn't go nearly far enough), fools rarely know they are fools and so they trumpet their foolishness as if it were wisdom. It's embarrassing, but what can you do?

**Comment by ckygel** [comment]
I liked the notion of 1x because there's too much craze and praise for productivity when in reality those people were cutting corners to get work done fast, then years down the line other people pick up the debt for them. 

From my experience 1x engineers can be assholes, and 10x engineers can be assholes too. The difference is  just a matter of perspective on problem-solving and life. 1x engineers tend to produce reliable results, but can miss critical times for delivering product market fit. 10x engineers can potentially launch great products, but will need 1x engineers to maintain them.

**Comment by mstomar698** [comment]
u guys really are discriminating on the basis of  once productivity.
Does efforts doesn't matter.
